"""Telegram Bot Handlers for Instagram Account Integration & Auto-Posting."""

import logging
from pathlib import Path
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ContextTypes

from bot.services.instagram_service import instagram_service
from bot.services.caption_generator import generate_instagram_caption
from database.db import db_manager

from typing import Dict, Any

logger = logging.getLogger(__name__)

# Cache pending 2FA login attempts: chat_id -> {username, password}
PENDING_2FA: Dict[int, Dict[str, str]] = {}


async def insta_login_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_login <username> <password> securely."""
    chat_id = update.effective_chat.id
    msg = update.effective_message

    # Safety: delete user message containing password immediately
    try:
        await context.bot.delete_message(chat_id=chat_id, message_id=msg.message_id)
    except Exception as e:
        logger.warning(f"Could not delete login message for security: {e}")

    args = context.args or []
    if len(args) < 2:
        help_text = (
            "ℹ️ **Instagram Login Usage:**\n\n"
            "`/insta_login <username> <password>`\n\n"
            "🔒 *Security Guarantee:* Your message containing your password is deleted "
            "from Telegram immediately. The session cookie is saved locally so you never have to re-enter it."
        )
        await context.bot.send_message(
            chat_id=chat_id,
            text=help_text,
            parse_mode="Markdown"
        )
        return

    username = args[0].strip().lstrip("@")
    password = args[1].strip()

    status_msg = await context.bot.send_message(
        chat_id=chat_id,
        text=f"⏳ *Connecting to Instagram as @{username}...* Please wait 5-10 seconds.",
        parse_mode="Markdown"
    )

    res = await instagram_service.login_user(chat_id, username, password)

    if res.get("success"):
        success_text = (
            f"✅ *Successfully Connected to Instagram!*\n\n"
            f"👤 **Account:** @{username}\n"
            f"✨ **Full Name:** {res.get('full_name', '')}\n\n"
            "Reels generated by this bot can now be published directly or saved to Drafts!\n\n"
            "• Use `/insta_autopost on` to post every reel automatically upon creation.\n"
            "• Use `/insta_status` to view account details."
        )
        await status_msg.edit_text(success_text, parse_mode="Markdown")
    else:
        if res.get("requires_2fa"):
            PENDING_2FA[chat_id] = {"username": username, "password": password}
            await status_msg.edit_text(
                "🔐 *Two-Factor Authentication (2FA) Required!*\n\n"
                "Instagram ne aapke phone / authenticator app par verification code bheja hai.\n\n"
                "Code verify karne ke liye ye command run karein:\n"
                "`/insta_2fa <code>`\n\n"
                "_(Example: `/insta_2fa 123456`)_",
                parse_mode="Markdown"
            )
            return

        err = res.get("error", "Unknown error occurred.")
        await status_msg.edit_text(
            f"❌ *Instagram Connection Failed:*\n\n{err}\n\nTry again with `/insta_login <username> <password>` or connect via session cookie with `/insta_session`.",
            parse_mode="Markdown"
        )


async def insta_2fa_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_2fa <code> to complete two-factor authentication."""
    chat_id = update.effective_chat.id
    msg = update.effective_message
    try:
        await context.bot.delete_message(chat_id=chat_id, message_id=msg.message_id)
    except Exception:
        pass

    pending = PENDING_2FA.get(chat_id)
    if not pending:
        await context.bot.send_message(
            chat_id=chat_id,
            text="❌ *No pending 2FA login found.*\nPlease run `/insta_login <username> <password>` first.",
            parse_mode="Markdown"
        )
        return

    args = context.args or []
    if not args:
        await context.bot.send_message(
            chat_id=chat_id,
            text="ℹ️ *Usage:* `/insta_2fa <code>`\nExample: `/insta_2fa 123456`\nSend the 6-digit verification code sent to your phone or authenticator app.",
            parse_mode="Markdown"
        )
        return

    code = args[0].strip()
    status_msg = await context.bot.send_message(
        chat_id=chat_id,
        text="⏳ *Verifying 2FA code with Instagram...*",
        parse_mode="Markdown"
    )

    res = await instagram_service.login_user(
        chat_id=chat_id,
        username=pending["username"],
        password=pending["password"],
        verification_code=code,
    )

    if res.get("success"):
        PENDING_2FA.pop(chat_id, None)
        await status_msg.edit_text(
            f"✅ *Successfully Connected to Instagram!*\n\n"
            f"👤 **Account:** @{pending['username']}\n"
            f"✨ **Full Name:** {res.get('full_name', '')}\n\n"
            "Auto-posting is now fully active for this account! 🚀",
            parse_mode="Markdown"
        )
    else:
        await status_msg.edit_text(
            f"❌ *2FA Verification Failed:*\n\n{res.get('error', 'Invalid code')}\n\nTry sending the code again: `/insta_2fa <code>`",
            parse_mode="Markdown"
        )


async def insta_session_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_session <sessionid> securely without passwords."""
    chat_id = update.effective_chat.id
    msg = update.effective_message

    # Safety: delete user message containing sessionid immediately
    try:
        await context.bot.delete_message(chat_id=chat_id, message_id=msg.message_id)
    except Exception as e:
        logger.warning(f"Could not delete session message for security: {e}")

    args = context.args or []
    if not args:
        help_text = (
            "ℹ️ **Instagram Session Login Usage:**\n\n"
            "`/insta_session <sessionid_cookie>`\n\n"
            "💡 *How to get your sessionid in 15 seconds (from Brave/Chrome):*\n"
            "1. Open [instagram.com](https://www.instagram.com) in Brave (where you are logged in)\n"
            "2. Press `F12` on keyboard (Developer Tools)\n"
            "3. Click **Application** (or Storage) tab on top\n"
            "4. Expand **Cookies** on the left -> click `https://www.instagram.com`\n"
            "5. Double-click the value next to `sessionid` and copy it!\n"
            "6. Send `/insta_session <copied_value>` here.\n\n"
            "🔒 *Security:* Your message is deleted immediately. Zero password or 2FA checks needed!"
        )
        await context.bot.send_message(
            chat_id=chat_id,
            text=help_text,
            parse_mode="Markdown"
        )
        return

    sessionid = args[0].strip()

    status_msg = await context.bot.send_message(
        chat_id=chat_id,
        text="⏳ *Authenticating with Instagram session cookie...* Please wait 5-10 seconds.",
        parse_mode="Markdown"
    )

    res = await instagram_service.login_with_sessionid(chat_id, sessionid)

    if res.get("success"):
        username = res.get("username", "")
        success_text = (
            f"✅ *Successfully Connected to Instagram!*\n\n"
            f"👤 **Account:** @{username}\n"
            f"✨ **Full Name:** {res.get('full_name', '')}\n\n"
            "Reels generated by this bot can now be published directly or saved to Drafts!\n\n"
            "• Use `/insta_autopost on` to post every reel automatically upon creation.\n"
            "• Use `/insta_status` to view account details."
        )
        await status_msg.edit_text(success_text, parse_mode="Markdown")
    else:
        err = res.get("error", "Unknown error occurred.")
        await status_msg.edit_text(
            f"❌ *Instagram Connection Failed:*\n\n{err}\n\nMake sure your sessionid is copied accurately from Brave.",
            parse_mode="Markdown"
        )



async def insta_status_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_status to check account link state."""
    chat_id = update.effective_chat.id
    acc = await instagram_service.is_connected(chat_id)

    if not acc:
        no_acc_text = (
            "📸 *No Instagram Account Connected*\n\n"
            "Connect your account using:\n"
            "`/insta_login <username> <password>`\n\n"
            "Once linked, you can post reels with 1-click or enable automatic publishing!"
        )
        await context.bot.send_message(chat_id=chat_id, text=no_acc_text, parse_mode="Markdown")
        return

    username = acc["username"]
    autopost = "🟢 Enabled (Every reel auto-posts)" if acc.get("auto_post") else "⚪ Disabled (Post manually via button)"

    status_text = (
        f"📸 *Connected Instagram Account*\n\n"
        f"👤 **Username:** @{username}\n"
        f"🔄 **Auto-Posting:** {autopost}\n\n"
        "⚙️ **Available Commands:**\n"
        "• `/insta_autopost on` - Automatically publish every new reel\n"
        "• `/insta_autopost off` - Publish only when you tap 'Post' button\n"
        "• `/insta_logout` - Disconnect this account"
    )
    await context.bot.send_message(chat_id=chat_id, text=status_text, parse_mode="Markdown")


async def insta_autopost_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Toggle /insta_autopost on|off."""
    chat_id = update.effective_chat.id
    args = context.args or []

    if not args or args[0].lower() not in ("on", "off", "enable", "disable"):
        await context.bot.send_message(
            chat_id=chat_id,
            text="Usage: `/insta_autopost on` or `/insta_autopost off`",
            parse_mode="Markdown"
        )
        return

    turn_on = args[0].lower() in ("on", "enable")
    success = await instagram_service.set_autopost(chat_id, turn_on)

    if not success:
        await context.bot.send_message(
            chat_id=chat_id,
            text="❌ Please connect your account first with `/insta_login <username> <password>`.",
            parse_mode="Markdown"
        )
        return

    state_str = "🟢 **Enabled**" if turn_on else "⚪ **Disabled**"
    confirm_text = (
        f"✅ Instagram Auto-Posting is now {state_str}!\n"
        + ("Every new reel will automatically be published to your feed." if turn_on else "New reels will display a Post to Instagram button.")
    )
    await context.bot.send_message(chat_id=chat_id, text=confirm_text, parse_mode="Markdown")


async def insta_logout_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_logout to unlink account."""
    chat_id = update.effective_chat.id
    await instagram_service.logout(chat_id)
    await context.bot.send_message(
        chat_id=chat_id,
        text="👋 *Instagram account disconnected successfully.*",
        parse_mode="Markdown"
    )


async def handle_post_to_insta_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle inline button callback: post_insta."""
    query = update.callback_query
    await query.answer()

    chat_id = update.effective_chat.id
    session = await db_manager.get_session(chat_id)

    if not session or not session.get("output_path"):
        await query.edit_message_reply_markup(reply_markup=None)
        await context.bot.send_message(
            chat_id=chat_id,
            text="❌ No recent reel found to post. Generate a new reel first!"
        )
        return

    video_path = Path(session["output_path"])
    if not video_path.exists():
        await context.bot.send_message(
            chat_id=chat_id,
            text=f"❌ Video file not found: {video_path.name}"
        )
        return

    hook_text = session.get("overlay_text") or "Late night thoughts 🌚💋"
    style = session.get("selected_template") or "sexy"

    # Generate viral caption & hashtags
    caption = generate_instagram_caption(hook_text, style=style)

    await query.edit_message_reply_markup(reply_markup=None)
    status_msg = await context.bot.send_message(
        chat_id=chat_id,
        text="🚀 *Uploading Reel to Instagram...* Please wait a moment.",
        parse_mode="Markdown"
    )

    res = await instagram_service.upload_reel(chat_id, video_path, caption=caption)

    if res.get("success"):
        post_url = res.get("url") or "Instagram Feed"
        await status_msg.edit_text(
            f"🎉 *Reel Successfully Published to Instagram!*\n\n"
            f"🔗 [View Live Reel on Instagram]({post_url})\n\n"
            f"📝 **Caption Used:**\n```\n{caption}\n```",
            parse_mode="Markdown",
            disable_web_page_preview=False
        )
    else:
        err = res.get("error", "Upload failed.")
        await status_msg.edit_text(
            f"❌ *Instagram Upload Failed:*\n\n{err}",
            parse_mode="Markdown"
        )


async def insta_graph_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_graph <account_id> <access_token> for zero-ban official Meta API connection."""
    chat_id = update.effective_chat.id
    msg = update.effective_message

    # Safety: delete user message containing access token immediately
    try:
        await context.bot.delete_message(chat_id=chat_id, message_id=msg.message_id)
    except Exception as e:
        logger.warning(f"Could not delete graph token message: {e}")

    args = context.args or []
    if len(args) < 2:
        help_text = (
            "🛡️ *Official Meta Graph API Setup (Zero Ban Risk)*\n\n"
            "Usage:\n"
            "`/insta_graph <INSTAGRAM_ACCOUNT_ID> <ACCESS_TOKEN>`\n\n"
            "📌 **Where to get these:**\n"
            "1. Open [Meta Graph API Explorer](https://developers.facebook.com/tools/explorer/)\n"
            "2. Select your Meta App (`Shruti Social Hub` or `sumit_99`)\n"
            "3. Generate Token with `instagram_basic` & `instagram_content_publish`\n"
            "4. Copy your numerical Instagram Account ID and paste here!\n\n"
            "🔒 *Security:* Your message with the token was automatically deleted from chat."
        )
        await context.bot.send_message(chat_id=chat_id, text=help_text, parse_mode="Markdown")
        return

    account_id = args[0].strip()
    access_token = args[1].strip()

    status_msg = await context.bot.send_message(
        chat_id=chat_id,
        text="⏳ *Verifying Meta Graph API credentials with Facebook servers...*",
        parse_mode="Markdown",
    )

    from bot.services.graph_api_service import graph_api_service
    check = await graph_api_service.verify_credentials(account_id, access_token)

    if check.get("valid"):
        username = check.get("username", "night_thought_12")
        await instagram_service.set_graph_credentials(chat_id, account_id, access_token, username=username)
        await status_msg.edit_text(
            f"🎉 *Official Meta Graph API Connected!*\n\n"
            f"• 👤 **Account:** @{username}\n"
            f"• 🆔 **Account ID:** `{account_id}`\n"
            f"• 🛡️ **Status:** **Zero Ban Risk Enabled** (Official Whitelisted Meta API)\n\n"
            f"All future scheduled reels will be published directly via Meta's official server-to-server endpoints! 🚀",
            parse_mode="Markdown",
        )
    else:
        err = check.get("error", "Unknown Meta error")
        await status_msg.edit_text(
            f"❌ *Meta Graph API Verification Failed:*\n\n`{err}`\n\n"
            f"Please verify that the Token has `instagram_content_publish` and `instagram_basic` permissions.",
            parse_mode="Markdown",
        )


async def insta_graph_status_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle /insta_graph_status to verify current connection mode."""
    chat_id = update.effective_chat.id
    graph_creds = await instagram_service.get_graph_credentials(chat_id)

    if graph_creds:
        from bot.services.graph_api_service import graph_api_service
        check = await graph_api_service.verify_credentials(graph_creds["account_id"], graph_creds["access_token"])
        status_text = "🟢 Active & Valid" if check.get("valid") else f"🔴 Invalid/Expired: {check.get('error')}"
        await update.effective_message.reply_text(
            f"🛡️ *Instagram Publishing Engine: Official Meta Graph API*\n\n"
            f"• 👤 **Account:** @{graph_creds.get('username')}\n"
            f"• 🆔 **Account ID:** `{graph_creds.get('account_id')}`\n"
            f"• 🔐 **Token Status:** {status_text}\n"
            f"• 🚀 **Ban Risk:** **0% (Meta Whitelisted)**\n\n"
            f"To re-link or update: `/insta_graph <account_id> <access_token>`",
            parse_mode="Markdown",
        )
    else:
        acc = await instagram_service.is_connected(chat_id)
        if acc:
            await update.effective_message.reply_text(
                f"⚠️ *Current Mode: Private Mobile Session (instagrapi)*\n\n"
                f"• Account: @{acc.get('username')}\n"
                f"• Stack: Private mobile emulation\n\n"
                f"💡 *Upgrade to Official Meta Graph API (Zero Ban Risk):*\n"
                f"Run `/insta_graph <account_id> <access_token>`",
                parse_mode="Markdown",
            )
        else:
            await update.effective_message.reply_text(
                "❌ No Instagram account connected yet.\nUse `/insta_graph` or `/insta_login`.",
                parse_mode="Markdown",
            )
